#!/bin/bash

do_settings() { \
      options=("Full" "Basic" "quit")

     echo "Do you want to do a full install or just get my configs? (basic install)"

     # Print the menu prompt and allow the user to select an option
      select default_choice in "${options[@]}"
      do
          case $default_choice in
              "Full")
                  tput setaf 2 && echo "You did choose to do a full install"
                  INSTALL_TYPE=full
                  tput sgr0
                  break
                  ;;
              "Basic")
                  tput setaf 2 && echo "You did choose to do a basic install"
                  INSTALL_TYPE=basic
                  tput sgr0
                  break
                  ;;
              "quit")
                  echo "Exiting..."
                  exit
                  ;;
              *)
                  tput setaf 1 && echo "Invalid option. Please select a valid option."
                  tput sgr0
                  ;;
          esac
      done

      read -p "Press to continue"
}

do_shell() { \

     # Define an array of shell options
     options=("bash" "zsh" "fish" "quit")

      echo "Please Choose your Default Shell"

     # Print the menu prompt and allow the user to select an option
     select shell_option in "${options[@]}"
     do
         case $shell_option in
             "bash")
                 SHELL_CHOICE="bash"
                 break
                 ;;
             "zsh")
                 SHELL_CHOICE="zsh"
                 break
                 ;;
             "fish")
                 SHELL_CHOICE="fish"
                 break
                 ;;
             "quit")
                 echo "Exiting..."
                 exit
                 ;;
             *)
                 echo "Invalid option. Please select a valid option."
                 ;;
         esac
     done


}

do_browser() { \

     declare -a browser=(

     "librewolf"
     "brave"
     "qutebrowser"
     "firefox"
     "chromium")

for installed_browser in $(printf '%s\n' "${browser[@]}") ; do

INSTALLED_BROWSERS=$(ls /usr/share/applications | grep $installed_browser)

_INSTALLED=$(echo "$INSTALLED_BROWSERS" "$_INSTALLED" )

done

if [ -z "$_INSTALLED" ] ; then

    echo "##########################################"
    echo "#No browser, Installed nothing to do here#"
    echo "##########################################"

else

    read -p "Please Select your default browser: Enter to continue"

    clear

    while [ -z $choice ] ; do

    choice=$( printf '%s\n' "${_INSTALLED[@]}" | xargs -n 1 | fzf )

    [ -z $choice ] && echo "you didn't make a choice. Make a choice kiddo"

    sleep 1

    done

    xdg-settings set default-web-browser $choice
fi

}


do_windowmanager() { \

     # Define an array of windowmanager options
     options=("Hyprland" "Qtile" "Quit")

      echo "Please Choose your Window Manager"

     # Print the menu prompt and allow the user to select an option
     select shell_option in "${options[@]}"
     do
         case $shell_option in
             "Hyprland")
                 WINDOW_MANAGER=hyprland
                 break
                 ;;
             "Qtile")
                 WINDOW_MANAGER=qtile
                 break
                 ;;
             "Quit")
                 echo "Exiting..."
                 exit
                 ;;
             *)
                 echo "Invalid option. Please select a valid option. Hyprland or Qtile"
                 ;;
         esac
     done


}

do_restart() { \

     # Define the options
     options=("yes" "No")


      echo "###############################################"
      echo "## Everything is done do you want to Reboot? ##"
      echo "###############################################"

     # Print the menu prompt and allow the user to select an option
     select restart_option in "${options[@]}"
     do
         case $restart_option in
             "yes")
                 sudo reboot
                 break
                 ;;
             "no")
                 echo "###########################"
                 echo "## We are not restarting ##"
                 echo "###########################"
                 break
                 ;;
             *)
                 echo "Invalid option. Please select yes or no"
                 ;;
         esac
     done

}
