#!/bin/bash

do_settings() { \
      options=("Full" "Basic" "quit")

     echo "Do you want to do a full install or just get my configs? (basic install)"

     # Print the menu prompt and allow the user to select an option
      select default_choice in "${options[@]}"
      do
          case $default_choice in
              "Full")
                  tput setaf 2 && echo "You did choose to do a full install"
                  INSTALL_TYPE=full
                  tput sgr0
                  break
                  ;;
              "Basic")
                  tput setaf 2 && echo "You did choose to do a basic install"
                  INSTALL_TYPE=basic
                  tput sgr0
                  break
                  ;;
              "quit")
                  echo "Exiting..."
                  exit
                  ;;
              *)
                  tput setaf 1 && echo "Invalid option. Please select a valid option."
                  tput sgr0
                  ;;
          esac
      done

      read -p "Press to continue"
}

do_shell() { \

     # Define an array of shell options
     options=("bash" "zsh" "fish" "quit")

      echo "Please Choose your Default Shell"

     # Print the menu prompt and allow the user to select an option
     select shell_option in "${options[@]}"
     do
         case $shell_option in
             "bash")
                 echo "You selected Bash as your default shell."
                 chsh -s /bin/bash $USER
                 break
                 ;;
             "zsh")
                 echo "You selected Zsh as your default shell."
                 chsh -s /bin/zsh $USER
                 break
                 ;;
             "fish")
                 echo "You selected Fish as your default shell."
                 chsh -s /usr/bin/fish $USER
                 break
                 ;;
             "quit")
                 echo "Exiting..."
                 exit
                 ;;
             *)
                 echo "Invalid option. Please select a valid option."
                 ;;
         esac
     done


}

do_browser() { \

declare -a browser=(

"librewolf"
"brave"
"qutebrowser"
"firefox"
"chromium"

)

for installed_browser in $(printf '%s\n' "${browser[@]}") ; do

INSTALLED_BROWSERS=$(ls /usr/share/applications | grep $installed_browser)

_INSTALLED=$(echo "$INSTALLED_BROWSERS" "$_INSTALLED" )

done

if [ -z "$_INSTALLED" ] ; then

    echo "you didn't make a choice. Make a choice kiddo"

else

    read -p "Please Select your default browser: Enter to continue"

    clear

    while [ -z $choice ] ; do

    choice=$( printf '%s\n' "${_INSTALLED[@]}" | xargs -n 1 | fzf )

    [ -z $choice ] && echo "you didn't make a choice. Make a choice kiddo"

    sleep 1

    done

    xdg-settings set default-web-browser $choice
fi

}


do_windowmanager() { \

     # Define an array of windowmanager options
     options=("Hyprland" "Qtile" "Quit")

      echo "Please Choose your Window Manager"

     # Print the menu prompt and allow the user to select an option
     select shell_option in "${options[@]}"
     do
         case $shell_option in
             "Hyprland")
                 break
                 ;;
             "Qtile")
                 break
                 ;;
             "Quit")
                 echo "Exiting..."
                 exit
                 ;;
             *)
                 echo "Invalid option. Please select a valid option."
                 ;;
         esac
     done


}

