#!/bin/bash

install-docker-portainer() {

docker -v &> /dev/null 

if [ $? = "0" ] ; then
       echo "###########################################################" 
       echo "## Installing Portainer agent so you can use this server ##"
       echo "## For docker containers only if its needed              ##"
       echo "###########################################################" 
       sleep 2    
       portainer_agent=$(sudo docker ps | awk '$NF == "portainer_agent" {print $NF}' 2> /dev/null)
       
       sudo docker volume create portainer_data_agent 
       
       [ "$portainer_agent" != "portainer_agent" ] && \
       sudo docker run -d -p 9001:9001 --name portainer_agent --restart=always \
       -v /var/run/docker.sock:/var/run/docker.sock  \
       -v portainer_data_agent:/var/lib/docker/volumes portainer/agent  
fi

sleep 2
clear

}
