#!/bin/bash
#This script contains functions to install some of my commonly used programs

install_qtile() { \

[ -d /etc/apt ] && sudo apt install -y python3-pip python3-cairocffi

    pip install xffib
    pip install qtile

    xsession_content=$(printf "[Desktop Entry]\n
    Name=Qtile\n
    Comment=This will start qtile wm\n
    Exec=/usr/bin/qtile start\n
    Type=Application"\n )

    printf '%s\n' "${xsession_content[@]}" | sed '/^ *$/d' > $HOME/qtile.desktop

    sudo mv $HOME/qtile.desktop /usr/share/xsessions

    sudo ln -s $HOME/.local/bin/qtile /usr/bin/qtile

    git clone https://github.com/elParaguayo/qtile-extras.git $HOME/qtile-extras

    cd $HOME/qtile-extras

    sudo python3 setup.py install

    cd -

    rm -rf $HOME/qtile-extras

}

install_uwufetch() { \

    git clone https://github.com/TheDarkBug/uwufetch.git $HOME/uwufetch

    cd $HOME/uwufetch

    sudo make install

    cd -

    rm -rf $HOME/uwufetch

}


install_btop() { \

    git clone https://github.com/aristocratos/btop.git $HOME/btop

    cd $HOME/btop

    make && sudo make install

    cd -

    rm -rf $HOME/btop
}

install_muttwizard() {\

    git clone https://github.com/LukeSmithxyz/mutt-wizard $HOME/mutt-wizard

    cd $HOME/mutt-wizard

    sudo make install

    cd -

    rm -rf $HOME/mutt-wizard

}

install_slock() { \

    git clone https://github.com/phoenix988/slock.git $HOME/slock

    cd $HOME/slock

    sed -i "s|nobody|$USER|g" config.def.h
    sed -i "s|nogroup|$USER|g" config.def.h

    rm -rf config.h

    sudo make install

    cd -

    rm -rf $HOME/slock

}




install_oh_my_tmux() { \

     # Clones oh my tmux
     [ -d $HOME/.tmux ] && cp -r $HOME/.tmux $HOME/.tmux.bak
      
     rm -rf $HOME/.tmux
         
     git clone https://github.com/gpakosz/.tmux.git  $HOME/.tmux

     clear

     [ -e $HOME/.tmux.conf ] && cp $HOME/.tmux.conf.bak
     
       rm $HOME/.tmux.conf
  
       ln -s $HOME/.tmux/.tmux.conf $HOME/.tmux.conf

       clear
}


install_fonts() {

    git clone https://github.com/phoenix988/fonts.git $HOME/fonts

    [ -d $HOME/.local/share/fonts ] || mkdir -p $HOME/.local/share/fonts

    sudo cp -r $HOME/fonts/fonts/* $HOME/.local/share/fonts

    rm -rf $HOME/fonts &> /dev/null

    sleep 1

}

install_picom() { \

    git clone https://github.com/jonaburg/picom $HOME/picom

    cd $HOME/pciom

    meson --buildtype=release . build

    ninja -C build

    sudo ninja -C build install

    cd -

    rm -rf $HOME/picom

}

install_pfetch() { \

    git clone https://github.com/dylanaraps/pfetch.git $HOME/pfetch

    cd $HOME/pfetch

    sudo make install

    cd -

    rm -rf $HOME/pfetch

}
