#!/bin/bash

error() { \
    clear; printf "ERROR:\\n%s\\n" "$1" >&2; exit 1;
}


welcome() { \
    dialog --colors --title "\Z7\ZbConfigure your Desktop!" --msgbox "\Z4This is a script that will install everythinging I personally use on a daily basis, This script will run using your Normal User account but sometimes it will need root privleges so then its gonna prompt you for a password to make sure to be near your computer. Me personally tho deactivate sudo password prompts but that comes with a security risk hehe. And also if you run this script when you are installing arch linux then it will install everything you need to get started with a base install. But you will need to run this script again when you have installed the base installation of arch \\n\\n-Karl" 16 60
    }

Lastchance() { \
        dialog --colors --title "\Z7\ZbPoint of no Return" --yes-label "Yes Continue with the install" --no-label "No" --yesno "\Z4Up to this point No changes Have been Made. But now the installation will begin if you click yes there will be no going back. Are you sure you want to do this?" 8 60 || error "user choose to exist"
    }

command_exist() {
        type "$1" &> /dev/null;
}


function case_text() {

      echo "######################################################################"
      echo "${RED}Invalid option: -$OPTARG." 1>&2
      echo "-f for a full install"
      echo "-c for only my config files and a few of my terminal applications"
      echo "-w (hyprland, qtile, xmonad)"
      echo "-s (zsh, bash, fish)"
      echo "-d for just my dotfiles,zsh,tmux and starship prompt"
      echo "-n for no config files (so you wont overwrite your current configs"
      echo "######################################################################"

}
