#!/bin/bash
#
function install_text(){

echo "Installing $1"

}

function case_text() {

      echo "Invalid option: -$OPTARG." 1>&2
      echo "-w (hyprland, qtile, xmonad)"
      echo "-s (zsh, bash, fish)"
      echo "-d for just my dotfiles,zsh,tmux and starship prompt"
      echo "-n for no config files (so you wont overwrite your current configs"

}
