#!/bin/bash

# here I add all the packages to install.
# Only pacman is supprted

# Declare function for pacman
install_pacman_full(){

declare -a packages=(
    "alsa-utils"
    "base-devel"
    "bat"
    "btop"
    "conky"
    "cronie"
    "curl"
    "dunst"
    "emacs"
    "exa"
    "feh"
    "fish"
    "flameshot"
    "git"
    "htop"
    "kitty"
    "lsd"
    "lxappearance"
    "lxsession"
    "ncspot"
    "neofetch"
    "neomutt"
    "neovim"
    "net-tools"
    "network-manager-applet"
    "nfs-utils"
    "noto-fonts"
    "openssh"
    "pavucontrol"
    "pcmanfm"
    "pipewire"
    "pipewire-pulse"
    "psmisc"
    "python-psutil"
    "qt5"
    "qt5ct"
    "qt5-quickcontrols2"
    "qt6ct"
    "ripgrep"
    "rofi"
    "rsync"
    "sddm"
    "sxiv"
    "tmux"
    "ttf-jetbrains-mono"
    "ttf-iosevka-nerd"
    "unzip"
    "vifm"
    "volumeicon"
    "wget"
    "xfce4-settings"
    "yad"
    "zip"
    "zsh")

sudo pacman -S --noconfirm --needed $(printf '%s\n' "${packages[@]}")

}

install_pacman_base() {

declare -a packages=(
      "base-devel"
      "bat"
      "btop"
      "cronie"
      "curl"
      "exa"
      "fish"
      "git"
      "htop"
      "lsd"
      "neofetch"
      "neomutt"
      "neovim"
      "net-tools"
      "nfs-utils"
      "openssh"
      "rsync"
      "tmux"
      "unzip"
      "vifm"
      "wget"
      "zip"
      "zsh")

sudo pacman -S --noconfirm --needed $(printf '%s\n' "${packages[@]}")

}
