#!/bin/bash

GTK_theme() { \

     git clone https://github.com/Fausto-Korpsvart/Rose-Pine-GTK-Theme.git $HOME/rose-pine
     git clone https://github.com/phoneix988/Nord-icons.git $HOME/nord-icons
     git clone https://github.com/phoneix988/Nord.git $HOME/nord

     wget https://github.com/dracula/gtk/archive/master.zip
     unzip master.zip ; cp -r master-gtk /usr/share/themes/dracula 
     rm master.zip ; rm -rf master-gtk 
     
     wget https://github.com/dracula/gtk/files/5214870/Dracula.zip
     unzip Dracula.zip ; cp -r Dracula /usr/share/icons/
     rm Dracula.zip ; rm -rf Dracula

     sudo  cp -r $HOME/rose-pine/themes/* /usr/share/themes/
     sudo  cp -r $HOME/rose-pine/icons/* /usr/share/icons/
     sudo  cp -r $HOME/nord /usr/share/themes/
     sudo  cp -r $HOME/nord-icons/NordArc-Theme /usr/share/icons/

     rm -rf $HOME/rose-pine
     rm -rf $HOME/nord
     rm -rf $HOME/nord-icons
}


sddm_theme() { \


     git clone https://gitlab.com/dwt1/multicolor-sddm-theme

     sudo mv multicolor-sddm-theme /usr/share/sddm/themes

     CURRENT="[Theme]"
     THEME="Current=multicolor-sddm-theme"

     echo $CURRENT | sudo tee /etc/sddm.conf
     echo $THEME | sudo tee -a /etc/sddm.conf

}

home_folders() {

    [ -d $HOME/Documents ] || mkdir $HOME/Documents
    [ -d $HOME/Downloads ] || mkdir $HOME/Pictures
    [ -d $HOME/Pictures ] || mkdir $HOME/Videos
    [ -d $HOME/Videos ] || mkdir $HOME/Videos

}
