#!/bin/bash

GTK_theme() { \

     git clone https://github.com/Fausto-Korpsvart/Rose-Pine-GTK-Theme.git $HOME/rose-pine

     sudo  cp -r $HOME/rose-pine/themes/* /usr/share/themes/
     sudo  cp -r $HOME/rose-pine/icons/* /usr/share/icons/


}


sddm_theme() { \

     CURRENT="[Theme]"
     THEME="Current=multicolor-sddm-theme"

     echo $CURRENT | sudo tee /etc/sddm.conf
     echo $THEME | sudo tee -a /etc/sddm.conf

}

home_folders() {

    [ -d $HOME/Documents ] || mkdir $HOME/Documents
    [ -d $HOME/Downloads ] || mkdir $HOME/Pictures
    [ -d $HOME/Pictures ] || mkdir $HOME/Videos
    [ -d $HOME/Videos ] || mkdir $HOME/Videos

}
