#!/bin/bash

gtk-theme() { \

theme_icon="Dracula"
theme_gtk="Dracula"

[ -d "$HOME/.config/gtk-3.0" ] || mkdir -p $HOME/.config/gtk-3.0  
[ -e "$HOME/.gtkrc-2.0" ] || touch $HOME/.gtkrc-2.0  

if [ -d /usr/share/themes/$theme_gtk ] ; then 
        echo "" &> /dev/null  
else
        wget https://github.com/dracula/gtk/archive/master.zip 

        unzip master.zip && sudo mv gtk-master /usr/share/themes/Dracula

        rm master.zip
fi

if [ -d /usr/share/icons/$theme_icon ] ; then 
        
        echo "" &> /dev/null  
else
        wget https://github.com/dracula/gtk/files/5214870/Dracula.zip
        unzip Dracula.zip && sudo mv Dracula /usr/share/icons/Dracula
        rm Dracula.zip
fi

check_gtk=$(grep "gtk-theme-name" "$HOME/.config/gtk-3.0/settings.ini" | awk -F "=" '{ print $NF }')

check_icon=$(grep "gtk-icon-theme-name" "$HOME/.config/gtk-3.0/settings.ini" | awk -F "=" '{ print $NF }')

if [ -z $check_icon ] ; then

   echo "gtk-icon-theme-name=Dracula" >> "$HOME/.config/gtk-3.0/settings.ini"

else
   
   sed  -i "s|$check_icon|$theme_icon|g" "$HOME/.config/gtk-3.0/settings.ini"

fi

if [ -z $check_gtk ] ; then

   echo "gtk-theme-name=Dracula" >> "$HOME/.config/gtk-3.0/settings.ini"

else
   
   sed  -i "s|$check_gtk|$theme_gtk|g" "$HOME/.config/gtk-3.0/settings.ini"

fi


}
