#!/bin/bash
# function to install my wallpapers

function wallpaper() {

[ -d $HOME/Pictures ] || mkdir $HOME/Pictures

[ -d $HOME/Pictures/Wallpapers/ ] || git clone https://github.com/phoenix988/wallpapers.git $HOME/wallpapers && echo "Wallpaper directory already exist"

cp -r $HOME/wallpapers/* $HOME/Pictures/

}
