#+title: SETUP UTILITY
#+author: Karl Fredin
#+DESCRIPTION: Utility to configure my desktop for arch

* IMPORTANT NOTICE
Don't just blindly run this script. Make sure you read it and know
what it does first. Because it can overwrite some of your current config files.
I don't recommend running this at all. This is mainly for me personally so I can quickly
configure a new install of arch linux. But if you are living on the edge feel free to try it.
But please do in a virtual machine.

* TABLE OF CONTENTS
- [[ABOUT]]
- [[FEATURES]]
- [[INSTALL]]
  - [[MAIN]]
  - [[EXAMPLES]]
- [[EXAMPLES.org][SAMPLES]]



* ABOUT
This is a project I am working on that will grab my config files and install my prefered
software on a new system to make reinstall easier. Right now only Arch is supported wont work
on debian base.

** FEATURES

** INSTALL
*** MAIN
To do a quick install you can just run main. The script will ask you the questions needed.
and you get to choose, window manager etc
#+begin_src sh
./main
#+end_src

*** EXAMPLES
Do a full installation, with zsh as default shell and qtile as window manager
#+begin_src sh
./main -w qtile -s zsh -f
#+end_src

Do a basic installation installing a few terminal applications and moves my custom configs to HOME
#+begin_src sh
./main -s zsh -c
#+end_src


** SAMPLES
Here you can look at screenshots of my configs
****** * [[EXAMPLES.org][SAMPLES]]
