#!/bin/bash

[ -d $HOME/.config/oh-my-zsh ] && git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $HOME/.config/oh-my-zsh/zsh-syntax-highlighting/
[ -d $HOME/.config/oh-my-zsh ] && git clone https://github.com/zsh-users/zsh-autosuggestions.git $HOME/.config/oh-my-zsh/zsh-autosuggestions/
[ -d $HOME/.config/oh-my-zsh ] && git clone https://github.com/softmoth/zsh-vim-mode.git $HOME/.config/oh-my-zsh/zsh-vim-mode/
