---
  - name: clones my repositories
    hosts: desktop
    tasks: 
      - name: clones my dotfiles repository  
        git:
          clone: yes
          dest: $HOME/dotfiles
          repo: https://github.com/phoenix988/dotfiles.git  

      - name: moving all my configs to .config in home      
        shell:
          cmd: cp -r $HOME/dotfiles/.config/* $HOME/.config
      
      - name: creating .local/share/applications if it doesn't exist      
        file:
          state: directory 
          dest: $HOME/.local/share/applications

      - name: moving some of my desktop files to home
        shell:
          cmd: cp -r $HOME/dotfiles/.local/share/applications/* $HOME/.local/share/applications

      - name: creating folder Documents/lists       
        file:  
          state: directory      
          dest: $HOME/Documents/lists

      - name: copying my script folder      
        shell:
          cmd: cp -r $HOME/dotfiles/.scripts $HOME

      - name: copying my dmenu folder      
        shell:
          cmd: cp -r $HOME/dotfiles/.dmenu $HOME

      - name: Templating some config files
        template: 
          src: "{{ item.src }}"
          dest: "{{ item.dest }}"
        with_items:
          - {src: "Home/dotfiles/.zshrc",dest: "Home/.zshrc"}
          - {src: "Home/dotfiles/.tmux.conf.local",dest: "Home/.tmux.conf.local"}
          - {src: "Home/dotfiles/Documents/lists/alias.list",dest: "Home/Documents/lists/alias.list"}
          - {src: "Home/dotfiles/.NERDTreeBookmarks",dest: "Home/.NERDTreeBookmarks"}
          - {src: "Home/dotfiles/.gtkrc-2.0",dest: "Home/.gtkrc-2.0"}

     


