---
  - name: clones my repositorys
    hosts: desktop
    tasks: 
      - name: clones my dotfiles repository  
        git:
          clone: yes
          dest: $HOME/dotfiles
          repo: https://github.com/phoenix988/dotfiles.git  
      - name: copying my config files      
        copy:
          remote_src: true
          dest: $HOME/.config  
          src: $HOME/dotfiles/.config  
       
     


