---
  - name: clones my repositorys
    hosts: desktop
    tasks: 
      - name: clones my dotfiles repository  
        git:
          clone: yes
          dest: $HOME/dotfiles
          repo: https://github.com/phoenix988/dotfiles.git  

      - name: moving all my configs to .config in home      
        shell:
          cmd: cp -r $HOME/dotfiles/.config/* $HOME/.config

      - name: creating folder Documents/lists       
        file:  
          state: directory      
          dest: $HOME/Documents/lists

      - name: copying my script folder      
        shell:
          cmd: cp -r $HOME/dotfiles/.scripts $HOME

      - name: copying my dmenu folder      
        shell:
          cmd: cp -r $HOME/dotfiles/.dmenu $HOME

      - name: Templating some config files
        template: 
          src: "{{ item.src }}"
          dest: "{{ item.dest }}"
        with_items:
          - {src: "home/dotfiles/.zshrc",dest: "home/.zshrc"}
          - {src: "home/dotfiles/.tmux.conf.local",dest: "home/.tmux.conf.local"}
          - {src: "home/dotfiles/Documents/lists/alias.list",dest: "home/Documents/lists/alias.list"}

     


