---
  - name: clones my repositorys
    hosts: desktop
    tasks: 
      - name: clones my dotfiles repository  
        git:
          clone: yes
          dest: $HOME/dotfiles
          repo: https://github.com/phoenix988/dotfiles.git  
      - name: moving all my configs to .config in home      
        shell:
          cmd: cp -r $HOME/dotfiles/.config $HOME/.config
     
     


