---
  - name: clones my repositorys
    hosts: desktop
    tasks: 
      - name: clones my dotfiles repository  
        git:
          clone: yes
          dest: $HOME/dotfiles
          repo: https://github.com/phoenix988/dotfiles.git  

      - name: moving all my configs to .config in home      
        shell:
          cmd: cp -r $HOME/dotfiles/.config/* $HOME/.config

      - name: creating folder Documents/lists       
        file:  
          state: directory      
          dest: $HOME/Documents/lists

      - name: gets my alias list and add it to Documents/lists
        copy:
          remote_src: yes
          src: $HOME/dotfiles/Documents/lists/alias.list
          dest: $HOME/Documents/lists/  

      - name: copying my script folder      
        shell:
          cmd: cp -r $HOME/dotfiles/.scripts $HOME

      - name: copying my dmenu folder      
        shell:
          cmd: cp -r $HOME/dotfiles/.dmenu $HOME

      - name: getting my tmux config
        copy:
          remote_src: yes
          src: $HOME/dotfiles/.tmux.conf.local
          dest: $HOME

      - name: getting my zshrc config
        copy:
          remote_src: yes
          src: $HOME/dotfiles/.zshrc 
          dest: $HOME
      
      - name: Templating some config files
        template: 
          src: "{{ item.src }}"
          dest: "{{ item.dest }}"
        with_items:
          - {src: "$HOME/dotfiles/.zshrc",dest: "$HOME/.zshrc"}
          - {src: "$HOME/dotfiles/.tmux.conf.local",dest: "$HOME/.tmux.conf.local"}

     


